### ISSUE TITLE
垂直居中不完全指南

### ISSUE THREAD

**Issue by Ganother** [Ganother/blog#2]
经验之谈，写前没有一一验证，欢迎指正
**line-height**
**单行**：line-height设置为所需的高度即可，[原理传送门 css line-height深入理解和应用
](http://www.zhangxinxu.com/wordpress/2009/11/css%E8%A1%8C%E9%AB%98line-height%E7%9A%84%E4%B8%80%E4%BA%9B%E6%B7%B1%E5%85%A5%E7%90%86%E8%A7%A3%E5%8F%8A%E5%BA%94%E7%94%A8/)
**多行 with vertical-align:middle** ：比较懒，直接粘的张大仙的例子,原理就是在末尾放一个空元素，但是要有占位的文字，比如空格，这个元素的line-height设置为想要的整块高度，例子中设置在了父元素上，因为line-height是继承哒。和主体两个不等高inline-block元素都添加vertical-align的时候，垂直对齐。如果是在移动端用这种方法，放个伪元素即可。
``` html
<p class="mulit_line">
    <span style="font-size:12px;">这里是高度为150像素的标签内的多行文字，文字大小为12像素。<br />这里是第二行，用来测试多行的显示效果。</span><i>&nbsp;</i>
</p>
```
``` css
.mulit_line{line-height:150px; border:1px dashed #cccccc; padding-left:5px;}
.mulit_line span{display:inline-block; line-height:1.4em; vertical-align:middle;}
.mulit_line i{width:0;display:inline-block; vertical-align:middle; font-size:0;}
```
**通过定位居中**
**普遍方法**
left:50%;top:50%;margin-left
