### ISSUE TITLE
项目积累

### ISSUE THREAD

**Issue by Ganother** [Ganother/blog#3]
# 移动端 
* **三星note呼出键盘，会取消掉最上面的margin，解决方案是改成padding**
* **IOS safari，页面进行滑动时，浏览器会把页面上的渲染进行锁定。**
* **移动端1px border：**
不支持after清浮动的方法，不支持有overflow的元素。
``` css
%top_border{
position: relative;
&:after{
content: "";
position: absolute;
top: 0;
left: 0;
right: 0;
height: 0;
border-bottom: 1px solid #ddd;
-webkit-transform: scaleY(0.5);
-webkit-transform-origin: 0 0;
}
}
%bottom_border{
position: relative;
&:after{
content: "";
position: absolute;
bottom: -1px;  // transform 不改变元素占位
left: 0;
right: 0;
height: 0;
border-bottom: 1px solid #ddd;
-webkit-transform: scaleY(0.5);
-webkit-transform-origin: 0 0;
}
}
```
* **部分移动端老浏览器不支持rotate3d(1,1,1,360deg), 改为分开写X，Y，Z**
* **部分移动端老浏览器伪元素动画失效，改为放一个真实元素**
* **transform并不改变元素占位，布局注意。**
* **IOS Safari 粘贴不触发keyup事件，改为input**
* **window.scrollTo(x,y)**部分机型不兼容
* **浏览器返回后，一般会重新执行js，然而ios不会，如果需要重新执行js，添加代码：**
``` javascript
if (/(iPhone|iPad|iPod)/i.test(navigator.userAgent)) {
    window.onpageshow = function (event) {
        if (event.persisted) { //假如页面是从缓存中得到
            window.location.reload() //直接刷新，或者重新调用需要调用的js
        }
    }
 };
```
* **微信中 输入框focus时会自动scroll，使focus事件里的scroll无效（有待进一步验证）。**
* **有一些机型 （华为 mate n）输入框focus时不会自动滚动使输入框出现在视野里，一定要添加scroll的行为。**
* **会将结果四舍五入的 jq width()，zepto width()、 offset().width， 原生offsetWidth、clientWidth。准确值，dom.getBoundingClientRect.width IE7\8不兼容**

# HTML CSS 布局
* **IE7，百分比宽度，或浏览器计算种出现小数，则会四舍五入成整数，导致子元素加起来不为100%，其它浏览器向下取整。**
* **垂直水平居中，兼容性良好，免计算**
``` html
<div style="position: relative; height: 500px;">
    <div style="position: absolute; top:0; bottom:0; left: 0; right:0; margin:auto; height:200px; width:70%"></div>
</div>
```
子div会表现为垂直居中，因为top:0 bottom:0 然而并不能上下间距都为0 ，这个时候的margin:auto;就会调节这个元素的实际所占空间，来满足上下为0，也就表现为了垂直居中。如果不加height：240px，则子div的高度沾满父div。
* **IE7 会忽略最底层margin-bottom，改为padding-bottom**
* **position:static或position:relative 应用动画会造成频繁的reflow(重新计算月面元素几何信息)。
position:absolute或position:fixed 应用动画只会触发repaint(重新绘制页面元素)**
* **IE 7、8空a是不可点的，需要加一个背景，background:url("about:blank");**
* **line-height:1.5  与 line-height:150%/1.5em的区别是后面的继承元素，前者的子元素会根据自己的font-size计算，后者则是使用父元素计算出来了的值，不会变动**
* **显式设置图片宽高，因为如果图片自身宽高和css样式设置不统一，浏览器还要处理，所以标签内最好也写上 width和height**
* **两栏自适应布局，左边固定尺寸，右边自适应**
``` css
.a{
float:left;
width: 30px;
margin-right: 30px;
}
.b{
overflow: hidden;
}
```
* **position为absolute的元素的 width height left top bottom right的百分比值都是根据它定位祖先元素的值确定的，具体是 width: 祖先元素width+padding;height: height+padding;left:width;top: height+padding**

# js相关
* **多次引用的对象属性，也用变量缓存起来**
* **setTimeOut，setInterval返回值为一个数字，意义为定时器ID，用来传入相应的clear函数**
* **获取元素高度，offsetWidth和offsetHeight之类需要触发layout(read)，设置宽高也会触发layout(write), 但是连续read或者连续write只会触发一次layout，所以写的顺序要注意。**
* **使用innerHtml或者html()代替createElement或appendChild();**
* **避免js二次解析，如setTimeout('test()',10);**
* **用数组的join函数代替+=进行字符串拼接。**
* **img标签获取dom后其实是个image对象，可以直接用onload属性，如果对img多次赋值，onload会重复调用**
* **img先绑定onload事件，再赋值 IEbug fix**
* **所有带有src，href的标签这个值不要为空，即<img src="" />这样会把当前页面再下载一次，用jq的attr获取的时候，也会得到当前页面的url，而不是空，用原生getAttribute（）可以得到空值**
* **typeof  Array,Null,Object都返回Object，判断是不是数组，用intanceof Array**
* **数组追加 Array.prototype.push.apply(array1, array2)**

# 其它
* **https页面中的http请求无效，debug时看下是否是这个原因。**
* **接口返回未登录可能是跨域了，ajax明明请求成功却进入error可能是返回的数据格式不对**
* **只有chrome支持1993-06-07这种时间格式，1993/06/07是通用的时间格式，然而数据库里一般拿到的都是前面这种，所以要转一下 new Date(Date.parse(time.replace(/-/g,"/"));**
