### ISSUE TITLE
新手初接触vuejs，写了个轮播组件

### ISSUE THREAD

**Issue by Ganother** [Ganother/blog#8]
新手第一次用vue，组件简单易懂，直接贴代码了，注释写的都很清楚
```html
<template>
  <section class="shuffling-wrapper">
    <ul :class="['shuffling-bar',{trans : open, transnext: openNext, transpre: openPre}]">
      <template v-for="item in shufflingData">
        <li
        :class="['item', {
          pre: $index == preIndex,
          next: $index == nextIndex,
          current: $index == shufflingIndex}]"
        :style="translateObj[$index]"
        @touchstart.prevent="touchStart($event)"
        @touchmove.prevent="touchMove($event)"
        @touchend.prevent="touchEnd($event)">
          <a class="link" href="{{item.link}}">
            <img class="img" :src="item.img" alt="{{item.title}}">
          </a>
        </li>
      </template>
      <li class="shuffling-btn">
        <i class="btn-item" :style="{width: btnWidth+'px', transform: 'translate3d('+(shufflingIndex*100)+'%,0,0)'}"></i>
      </li>
    </ul>

  </section>
</template>
```
``` css
  .shuffling-wrapper{
    width: 100%;
  }
  .shuffling-bar{
    position: relative;
    width: 100%;
    overflow: hidden;
    padding-top: 70.66%;
    .item{
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      margin: auto;
      z-index: 100;
    }
    .link{
      display: block;
      width: 100%;
      height: 100%;
    }
    .img{
      display: block;
      width: 100%;
      height: 100%;
    }

    .current{
      -webkit-transform: translate3d(0, 0, 0);
      z-index: 300;
    }
    .pre{
      -webkit-transform: translate3d(-100%, 0, 0);
      z-index: 300;
    }
    .next{
      -webkit-transform: translate3d(100%, 0, 0);
      z-index: 300;
    }
  }
  .trans{
    .current{
        -webkit-transition: transform .3s ease-in-out;
    }
  }
  .transpre{
    .pre{
        -webkit-transition: transform .3s ease-in-out;
    }
  }
  .transnext{
    .next{
        -webkit-transition: transform .3s ease-in-out;
    }
  }
  .shuffling-btn{
    height: 3px;
    background-color: rgba(255,255,255,.8);
    position: relative;
    z-index: 400;
    .btn-item{
      position: absolute;
      top: 0;
      left: 0;
      height: 3px;
      background-color: #e81926;
      border-radius: 1px;
      -webkit-transition: transform .3s ease-in-out;
    }
  }
</style>
```
```javascript
export default{
    ready: function(){ //初始化
      this.autoScroll(); //开始自动轮播
      this.caculateIndex(); //计算初始前一个元素，当前元素，后一个元素
      this.btnWidth = this.clientWidth/this.shufflingData.length;
    },
    data(){
      let that = this;
      return {
        shufflingData: [
          {
            title: "you pick me up",
            img: "http://img7.test.cm233.com/c766e437d5fd10b272497252791cbc27.jpg",
            link: "http://test.cm233.com/Phone/Book/detail?bookId=66"
          },
          {
            title: "pei, you raise me up",
            img: "http://img6.test.cm233.com/b15103ca7b9f372ace353245921388e6.jpg",
            link: "http://test.cm233.com/Phone/Book/detail?bookId=44"
          },
          {
            title: "pei, you raise me up",
            img: "http://resource.test.cm233.com/img/6f0c3269ad40cec1817ca68f512c9b91.jpg",
            link: "http://test.cm233.com/Phone/Book/detail?bookId=44"
          },
          {
            title: "pei, you raise me up",
            img: "http://resource.test.cm233.com/img/df327fbde526a647da982c36a1e60f31.jpg",
            link: "http://test.cm233.com/Phone/Book/detail?bookId=44"
          }
        ],
        shufflingIndex: 0, //当前元素的index
        nextIndex: 0, //后一个元素的序列
        preIndex: 0, //前一个元素的序列
        timer: 0, // 储存循环的计时器序号
        translateObj: { //touch事件时用来记录移动位置并应用到style中
          0: {},
          1: {},
          2: {},
          3: {},
          4: {},
          5: {}
        },
        open: true, // 当前元素的动画开关
        openNext: false, // 后一个元素的动画开关
        openPre: true, // 前一个元素的动画开关
        timeOut: false, // 和setTimeout一起可确保touch事件和之后的小动画完成后再执行自动轮播
        clientWidth: document.documentElement.getBoundingClientRect().width,
        btnWidth: 0
      }
    },
    methods: {
      touchStart(event){
        let that = this;
        clearInterval(that.timer);
        that.startX = event.changedTouches[0].pageX; //初始位置
        this.open = false;
        this.openPre = false;
      },
      touchMove(event){
        this.movingX = event.changedTouches[0].pageX; //移动中的位置
        this.percent = ((this.movingX-this.startX)/this.clientWidth)*100;
        //需要响应到style中的transform属性添加，必须要用$set方法，否则不会响应到视图
        this.$set('translateObj[preIndex].transform','translate3d('+(this.percent-100)+'%, 0, 0)');
        this.$set('translateObj[nextIndex].transform','translate3d('+(this.percent+100)+'%, 0, 0)');
        this.$set('translateObj[shufflingIndex].transform','translate3d('+(this.percent)+'%, 0, 0)');
      },
      touchEnd(){
        this.open = true;
        this.openPre = true;
        this.openNext = true;
        this.$set('translateObj[preIndex].transform','');
        this.$set('translateObj[nextIndex].transform','');
        this.$set('translateObj[shufflingIndex].transform','');
        if(!this.timeOut){
          this.timeOut = true;
          if(this.percent <= -50){ //假如向左滑了50%，则向左移动一屏，向左移动一屏需要关掉下一个元素的动画开关，否则后后一屏的元素会飞过去
            this.sufflingChange(); //向右侧滚动（包含最后一个元素时的处理）
            this.openNext = false;
          }else if(this.percent >= 50){ //假如向右滑了50%，则向右移动一屏，向右移动一屏需要关掉前一个元素的动画开关，否则前前一屏的元素会飞过去
            if(this.shufflingIndex == 0){ //向左侧滚动（包含第一个元素的处理）
              this.shufflingIndex = this.shufflingData.length-1;
            }else{
              this.shufflingIndex--;
            }
            this.openPre = false;
            this.caculateIndex();
          }
          setTimeout(() => { //确保移动后的动画完成，延迟和动画时间设置一致
            this.autoScroll();
            this.timeOut = false;
          }, 300);
        }
      },
      autoScroll(){ //进行自动轮播
        let that = this;
        that.openNext = false;
        that.openPre = true;
        that.timer = setInterval(that.sufflingChange,4000);
      },
      sufflingChange(){ //向右侧滚动
        if(this.shufflingIndex == this.shufflingData.length - 1){
          this.shufflingIndex = 0;
        }else{
          this.shufflingIndex++;
        }
        this.caculateIndex();
      },
      caculateIndex(){ //计算上一个元素和下一个元素的index
        this.preIndex = this.shufflingIndex - 1 < 0 ? this.shufflingData.length-1 : this.shufflingIndex - 1;
        this.nextIndex = this.shufflingIndex + 1 >= this.shufflingData.length ? 0 : this.shufflingIndex + 1;
      }
    }
  }
```
通过写这个组件对vue的数据驱动视图的思想更了解了嗯
